version: "3"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgresDB 
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@mail.com
      PGADMIN_DEFAULT_PASSWORD: password

